### PR TITLE
#3 - Add missing Alert Contact methods

### PR DESCRIPTION
**Pull request by MichalDolata**
I added missing methods for Alert Contact listed in #3 
____________
This is my first pull request for opensource project, so if u have any advice for me, I would be grateful.

### CODE REVIEW

**Comment by juhalehtonen** [comment]
Hey, and thank you for your contribution! I will have a closer look at your PR soon.

**Comment by juhalehtonen** [comment]
I checked this out now, and everything seems to work well. However, can you still do one more tweak and fix the documented example given on https://github.com/MichalDolata/ex_uptimerobot/blob/add-missing-alert-contact-methods/lib/ex_uptimerobot/alert_contact.ex#L88 , which currently refers to "new" instead of "edit". Once you've done that, I'll be happy to merge this :)

**Comment by MichalDolata** [comment]
I hope that now everything is OK :)

**Comment by juhalehtonen** [comment]
Great, merged up now! Thank you very much :)

**Pull request merged**
